In [1]:
# Importing necessary libraries
import pandas as pd
import seaborn as sns

In [3]:
# Read the file
df = pd.read_csv("cleaned_spam.csv")

In [4]:
df

      Unnamed: 0 Mail_Type                                       Mail_Message
0              0       ham  Go until jurong point, crazy.. Available only ...
1              1       ham                      Ok lar... Joking wif u oni...
2              2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3              3       ham  U dun say so early hor... U c already then say...
4              4       ham  Nah I don't think he goes to usf, he lives aro...
...          ...       ...                                                ...
5164        5567      spam  This is the 2nd time we have tried 2 contact u...
5165        5568       ham              Will Ì_ b going to esplanade fr home?
5166        5569       ham  Pity, * was in mood for that. So...any other s...
5167        5570       ham  The guy did some bitching but I acted like i'd...
5168        5571       ham                         Rofl. Its true to its name

[5169 rows x 3 columns]

In [6]:
df.drop(columns=['Unnamed: 0'],inplace=True)

In [7]:
df

     Mail_Type                                       Mail_Message
0          ham  Go until jurong point, crazy.. Available only ...
1          ham                      Ok lar... Joking wif u oni...
2         spam  Free entry in 2 a wkly comp to win FA Cup fina...
3          ham  U dun say so early hor... U c already then say...
4          ham  Nah I don't think he goes to usf, he lives aro...
...        ...                                                ...
5164      spam  This is the 2nd time we have tried 2 contact u...
5165       ham              Will Ì_ b going to esplanade fr home?
5166       ham  Pity, * was in mood for that. So...any other s...
5167       ham  The guy did some bitching but I acted like i'd...
5168       ham                         Rofl. Its true to its name

[5169 rows x 2 columns]

In [8]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z0-9]", " ", text)
    return text

df['Mail_Message'] = df['Mail_Message'].apply(clean_text)

In [9]:
df

     Mail_Type                                       Mail_Message
0          ham  go until jurong point  crazy   available only ...
1          ham                      ok lar    joking wif u oni
2         spam  free entry in 2 a wkly comp to win fa cup fina...
3          ham  u dun say so early hor    u c already then say
4          ham  nah i don t think he goes to usf  he lives aro...
...        ...                                                ...
5164      spam  this is the 2nd time we have tried 2 contact u...
5165       ham              will    b going to esplanade fr home
5166       ham  pity    was in mood for that  so   any other s...
5167       ham  the guy did some bitching but i acted like i d...
5168       ham                         rofl  its true to its name

[5169 rows x 2 columns]

In [10]:
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in c:\programdata\anaconda3\lib\site-packages (3.8.1)
Requirement already satisfied: click in c:\programdata\anaconda3\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: joblib in c:\programdata\anaconda3\lib\site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\programdata\anaconda3\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from nltk) (4.65.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [11]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Raman\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [24]:
import nltk
from nltk.corpus import stopwords
import string
from nltk.stem.porter import PorterStemmer
nltk.download('stopwords')
ps = PorterStemmer()

def transfrom_text(text):
    # Tokenization
    text = nltk.word_tokenize(text)
    y=[]
    
    # Removing Special character
    for i in text:
        if i.isalnum():
            y.append(i)
    
    text = y[:]
    y.clear()
    
    # Removing stopwords and punctuations
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)
    text = y[:]
    y.clear()
    
    # Stemming
    for i in text:
        y.append(ps.stem(i))
    text = y[:]
    y.clear()
    return " ".join(text) 


df['transformed_text'] = df['Mail_Message'].apply(transfrom_text)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Raman\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [25]:
df

,Mail_Type,Mail_Message,transformed_text
0,ham,go until jurong point crazy available only ...,go jurong point crazi avail bugi n great world...
1,ham,ok lar joking wif u oni,ok lar joke wif u oni
2,spam,free entry in 2 a wkly comp to win fa cup fina...,free entri 2 wkli comp win fa cup final tkt 21...
3,ham,u dun say so early hor u c already then say,u dun say earli hor u c alreadi say
4,ham,nah i don t think he goes to usf he lives aro...,nah think goe usf live around though
...,...,...,...
5164,spam,this is the 2nd time we have tried 2 contact u...,2nd time tri 2 contact u u 750 pound prize 2 c...
5165,ham,will b going to esplanade fr home,b go esplanad fr home
5166,ham,pity was in mood for that so any other s...,piti mood suggest
5167,ham,the guy did some bitching but i acted like i d...,guy bitch act like interest buy someth els nex...
5168,ham,rofl its true to its name,rofl true name

In [26]:
df.to_csv('preprocessed_dataset.csv')